apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "net.ipv6.conf.all.disable_ipv6=1"]
        securityContext:
          privileged: true
      containers:
        - name: radarr
          image: ghcr.io/hotio/radarr:latest
          imagePullPolicy: Always
          strategy:
            type: Recreate
          env:
            - name: PUID
              value: "5000"
            - name: PGID
              value: "5000"
            - name: TZ
              value: "Europe/Vienna"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: web
              containerPort: 7878
              protocol: TCP
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: data
          nfs:
            server: nas.schwarz47.at
            path: "/mnt/storage-media/tank"