
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: media-radarr-ingress
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`media.server.schwarz47.at`)
      services:
        - name: radarr-service
          port: 80
  tls:
    secretName: server-schwarz47-at-tls