apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: local-cluster-project
  source:
    path: apps/homeassistant
    repoURL: https://git.server.schwarz47.at/dominik/kubernetes.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homeassistant
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true