apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: mediaserver
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config