apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: ghcr.io/hotio/sabnzbd:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "5000"
            - name: PGID
              value: "5000"
            - name: TZ
              value: "Europe/Vienna"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: web
              containerPort: 5055
              protocol: TCP
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: data
          nfs:
            server: nas.schwarz47.at
            path: "/mnt/storage-media/tank/usenet"