apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "5000"
            - name: PGID
              value: "5000"
            - name: TZ
              value: "Europe/Vienna"
            - name: HAS_IPV6
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "1024Mi"
              cpu: "2"
            limits:
              memory: "2048Mi"
              cpu: "4"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: data
          nfs:
            server: nas.schwarz47.at
            path: "/mnt/storage-media/tank/usenet"