global:
  domain: argocd.server.schwarz47.at

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    paths:
      - /
    pathType: Prefix
  config:
    kustomize.buildOptions: --enable-helm