apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mediaserver
  namespace: media
spec:
  generators:
  - list:
      elements:
      - name: radarr
  template:
    metadata:
      name: 'media-{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/Calautigo/gitops.git
        targetRevision: main
        path: cluster-server-01/apps/media/arr/overlays/{{name}}
      destination:
        namespace: media
        server: https://kubernetes.default.svc