apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mediaserver
  namespace: mediaserver
spec:
  generators:
    - git:
        repoURL: https://github.com/Calautigo/gitops.git
        revision: main
        directories:
          - path: cluster-server-01/components/arr/overlays/*
  template:
    metadata:
      name: 'media-{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/Calautigo/gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        namespace: mediaserver
        server: https://kubernetes.default.svc