apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-arr
  namespace: mediaserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi