apiVersion: v1
kind: Service
metadata:
  namespace: homeassistant
  name: homeassistant-service
spec:
  selector:
    app: homeassistant
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homeassistant
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: linuxserver/homeassistant:2024.4.4
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "2.0"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config
          name: configmap-volume-configuration
        - mountPath: /config
          name: configmap-volume-automation
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-pvc
      - name: configmap-volume-automation
        configMap:
          name: homeassistant-configmap
          items:
          - key: automations.yaml
            path: automations.yaml
      - name: configmap-volume-configuration
        configMap:
          name: homeassistant-configmap
          items:
          - key: configuration.yaml
            path: configuration.yaml