apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
  labels:
    app: homeassistant
  namespace: homeassistant
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 