apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 10Gi 