apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: core-

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  version: v1.14.5
  valuesFile: values.yaml

resources:
- letsencrypt-production.yaml
- server-schwarz47-at.yaml